@echo off
setlocal EnableExtensions

cd /d "%~dp0"

set "ROOT=%CD%"
set "SRC_C=%ROOT%\src\c"
set "SRC_CS=%ROOT%\src\cs"
set "BUILD=%ROOT%\build"
set "OBJ=%BUILD%\obj"
set "NATIVE=%BUILD%\native"
set "APP=%BUILD%\app"
set "TOOLS=%BUILD%\tools"

rem The RP1210 side is x86, so force the Visual C++ toolchain to x86.
if /I "%VSCMD_ARG_TGT_ARCH%"=="x86" goto :toolchain_ready

echo [build] Switching Visual C++ toolchain to x86...

if defined VSINSTALLDIR (
    if exist "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" (
        call "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" x86
        if errorlevel 1 goto :fail
        goto :toolchain_ready
    )
)

set "VSWHERE="
for /f "delims=" %%I in ('where vswhere.exe 2^>nul') do if not defined VSWHERE set "VSWHERE=%%I"
if not defined VSWHERE (
    for /f "delims=" %%I in ('dir /b /s "%ProgramFiles(x86)%\vswhere.exe" 2^>nul') do if not defined VSWHERE set "VSWHERE=%%I"
)
if not defined VSWHERE (
    echo ERROR: Could not locate the installed compiler toolchain locator.
    goto :fail
)

set "VSROOT="
for /f "usebackq tokens=*" %%I in (`"%VSWHERE%" -latest -products * -property installationPath`) do set "VSROOT=%%I"

if not defined VSROOT (
    echo ERROR: Could not locate the x86 C/C++ toolchain.
    goto :fail
)

call "%VSROOT%\VC\Auxiliary\Build\vcvarsall.bat" x86
if errorlevel 1 goto :fail

:toolchain_ready
if /I not "%VSCMD_ARG_TGT_ARCH%"=="x86" (
    echo ERROR: MSVC target is "%VSCMD_ARG_TGT_ARCH%", not x86.
    goto :fail
)

where cl >nul 2>nul
if errorlevel 1 (
    echo ERROR: cl.exe was not found.
    goto :fail
)

where dotnet >nul 2>nul
if errorlevel 1 (
    echo ERROR: dotnet was not found. Install the .NET 10 SDK.
    goto :fail
)

rem Everything generated by this script lives under build\.
if exist "%BUILD%" rmdir /S /Q "%BUILD%"
mkdir "%OBJ%" "%NATIVE%" "%APP%" "%TOOLS%"
if errorlevel 1 goto :fail

echo [1/4] Building native RP1210/CLIP core...
pushd "%OBJ%"

cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /c ^
    "%SRC_C%\rp1210scan.c" ^
    "%SRC_C%\rp1210clip.c" ^
    "%SRC_C%\clip_crypto.c" ^
    "%SRC_C%\clip_cal.c" ^
    "%SRC_C%\ccal_crc.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /DLL /MACHINE:X86 ^
    /DEF:"%SRC_C%\rp1210scan.def" ^
    /OUT:"%NATIVE%\rp1210scan.dll" ^
    /IMPLIB:"%NATIVE%\rp1210scan.lib" ^
    /PDB:"%NATIVE%\rp1210scan.pdb" ^
    rp1210scan.obj rp1210clip.obj clip_crypto.obj clip_cal.obj ccal_crc.obj ^
    kernel32.lib user32.lib
if errorlevel 1 goto :fail_from_obj

echo [2/4] Building standalone UI config store...
cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /c ^
    /Fo:config_store.obj ^
    "%SRC_C%\config_store.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /DLL /MACHINE:X86 ^
    /DEF:"%SRC_C%\config_store.def" ^
    /OUT:"%NATIVE%\ctconfig.dll" ^
    /IMPLIB:"%NATIVE%\ctconfig.lib" ^
    /PDB:"%NATIVE%\ctconfig.pdb" ^
    config_store.obj kernel32.lib
if errorlevel 1 goto :fail_from_obj

echo [3/4] Building CRC utility...
cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /c "%SRC_C%\crc_call.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /MACHINE:X86 ^
    /OUT:"%TOOLS%\crc_call.exe" ^
    crc_call.obj ccal_crc.obj
if errorlevel 1 goto :fail_from_obj

popd

echo [4/4] Publishing WinForms app...
dotnet publish "%SRC_CS%\CalibrationTransfer.csproj" ^
    -c Release ^
    -r win-x86 ^
    --self-contained true ^
    -o "%APP%"
if errorlevel 1 goto :fail

echo.
echo Build complete:
echo   build\app\CalibrationTransfer.exe
echo   build\tools\crc_call.exe
echo.
echo Native/intermediate files are also contained under build\.
exit /b 0

:fail_from_obj
popd

:fail
echo.
echo BUILD FAILED
exit /b 1
