@echo off
setlocal EnableExtensions

cd /d "%~dp0"

set "ROOT=%CD%"
set "SRC_CORE=%ROOT%\src\core"
set "SRC_WINDOWS=%ROOT%\src\windows"
set "SRC_WIN_NATIVE=%SRC_WINDOWS%\native"
set "SRC_WIN_TOOLS=%SRC_WINDOWS%\tools"
set "BUILD=%ROOT%\build"
set "OBJ=%BUILD%\obj"
set "NATIVE=%BUILD%\native"
set "APP=%BUILD%\app"
set "TOOLS=%BUILD%\tools"

rem The RP1210 side is x86, so force the Visual C++ toolchain to x86.
if /I "%VSCMD_ARG_TGT_ARCH%"=="x86" goto :toolchain_ready

echo [build] Switching Visual C++ toolchain to x86...

if defined VSINSTALLDIR (
    if exist "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" (
        call "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" x86
        if errorlevel 1 goto :fail
        goto :toolchain_ready
    )
)

set "VSWHERE="
for /f "delims=" %%I in ('where vswhere.exe 2^>nul') do if not defined VSWHERE set "VSWHERE=%%I"
if not defined VSWHERE (
    for /f "delims=" %%I in ('dir /b /s "%ProgramFiles(x86)%\vswhere.exe" 2^>nul') do if not defined VSWHERE set "VSWHERE=%%I"
)
if not defined VSWHERE (
    echo ERROR: Could not locate the installed compiler toolchain locator.
    goto :fail
)

set "VSROOT="
for /f "usebackq tokens=*" %%I in (`"%VSWHERE%" -latest -products * -property installationPath`) do set "VSROOT=%%I"

if not defined VSROOT (
    echo ERROR: Could not locate the x86 C/C++ toolchain.
    goto :fail
)

call "%VSROOT%\VC\Auxiliary\Build\vcvarsall.bat" x86
if errorlevel 1 goto :fail

:toolchain_ready
if /I not "%VSCMD_ARG_TGT_ARCH%"=="x86" (
    echo ERROR: MSVC target is "%VSCMD_ARG_TGT_ARCH%", not x86.
    goto :fail
)

where cl >nul 2>nul
if errorlevel 1 (
    echo ERROR: cl.exe was not found.
    goto :fail
)

where dotnet >nul 2>nul
if errorlevel 1 (
    echo ERROR: dotnet was not found. Install the .NET 10 SDK.
    goto :fail
)

rem Everything generated by this script lives under build\.
if exist "%BUILD%" rmdir /S /Q "%BUILD%"
mkdir "%OBJ%" "%NATIVE%" "%APP%" "%TOOLS%"
if errorlevel 1 goto :fail

echo [1/4] Building native RP1210, J1939, and calibration protocol core...
pushd "%OBJ%"

cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /I"%SRC_CORE%" /I"%SRC_WIN_NATIVE%" /c ^
    "%SRC_WIN_NATIVE%\rp1210scan.c" ^
    "%SRC_WIN_NATIVE%\rp1210_transport.c" ^
    "%SRC_CORE%\j1939_transport.c" ^
    "%SRC_CORE%\ct_platform.c" ^
    "%SRC_CORE%\clip_transfer.c" ^
    "%SRC_CORE%\echo_transfer.c" ^
    "%SRC_CORE%\clip_crypto.c" ^
    "%SRC_CORE%\clip_cal.c" ^
    "%SRC_CORE%\ccal_crc.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /DLL /MACHINE:X86 ^
    /DEF:"%SRC_WIN_NATIVE%\rp1210scan.def" ^
    /OUT:"%NATIVE%\rp1210scan.dll" ^
    /IMPLIB:"%NATIVE%\rp1210scan.lib" ^
    /PDB:"%NATIVE%\rp1210scan.pdb" ^
    rp1210scan.obj rp1210_transport.obj j1939_transport.obj ct_platform.obj clip_transfer.obj echo_transfer.obj clip_crypto.obj clip46_poc_secure.obj clip_cal.obj ccal_crc.obj ^
    kernel32.lib user32.lib advapi32.lib
if errorlevel 1 goto :fail_from_obj

echo [2/4] Building standalone UI config store...
cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /I"%SRC_CORE%" /I"%SRC_WIN_NATIVE%" /c ^
    /Fo:config_store.obj ^
    "%SRC_CORE%\config_store.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /DLL /MACHINE:X86 ^
    /DEF:"%SRC_WIN_NATIVE%\config_store.def" ^
    /OUT:"%NATIVE%\ctconfig.dll" ^
    /IMPLIB:"%NATIVE%\ctconfig.lib" ^
    /PDB:"%NATIVE%\ctconfig.pdb" ^
    config_store.obj kernel32.lib
if errorlevel 1 goto :fail_from_obj

echo [3/4] Building CRC utility...
cl /nologo /W3 /O2 /TC /D_CRT_SECURE_NO_WARNINGS /I"%SRC_CORE%" /c "%SRC_WIN_TOOLS%\crc_call.c"
if errorlevel 1 goto :fail_from_obj

link /nologo /MACHINE:X86 ^
    /OUT:"%TOOLS%\crc_call.exe" ^
    crc_call.obj ccal_crc.obj
if errorlevel 1 goto :fail_from_obj

popd

echo [4/4] Publishing WinForms app...

set "RESTORE_ATTEMPT=0"

:restore_retry
set /A RESTORE_ATTEMPT+=1
echo [build] dotnet restore attempt %RESTORE_ATTEMPT% of 3...
dotnet restore "%SRC_WINDOWS%\CalibrationTransfer.csproj" -r win-x86
if not errorlevel 1 goto :restore_ok

if %RESTORE_ATTEMPT% GEQ 3 goto :fail
echo [build] Restore failed; retrying in 5 seconds...
powershell.exe -NoProfile -Command "Start-Sleep -Seconds 5"
goto :restore_retry

:restore_ok
dotnet publish "%SRC_WINDOWS%\CalibrationTransfer.csproj" ^
    -c Release ^
    -r win-x86 ^
    --self-contained true ^
    --no-restore ^
    -o "%APP%"
if errorlevel 1 goto :fail

echo.
echo Build complete:
echo   build\app\CalibrationTransfer.exe
echo   build\tools\crc_call.exe
echo.
echo Native/intermediate files are also contained under build\.
exit /b 0

:fail_from_obj
popd

:fail
echo.
echo BUILD FAILED
exit /b 1
