name: build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  windows-x86:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build
        shell: cmd
        run: build.bat
